chore: fix rocks terminology
canonical/prometheus-rock pull request #51
Opened 2024-05-22 16:57 UTC by cjdcordeiro

## Issue

"ROCK" should be "rock"

## Solution

Replacing all occurrences

## Context

## Testing Instructions

## Upgrade Notes

2024-05-23 07:54 UTC, mmkay requested changes
The changes are good, but most likely we'll need signed commits here as well.

2024-05-24 10:02 UTC, cjdcordeiro commented
The commit is now signed

2024-05-24 10:46 UTC, mmkay approved these changes

2024-05-24 10:46 UTC, merged

2024-05-24 10:46 UTC, mmkay commented
Thank you for the contribution, @cjdcordeiro! The PRs should now be merged.